#!/bin/bash
/usr/bin/screen -dmS Painter /bin/bash /home/dylski/projects/visplastica/paint_collages
echo "Run '/usr/bin/screen -r Painter' to see log"
#/usr/bin/tmux new-session -d -s "painter" /home/dylski/projects/visplastica/paint_collages
